FROM n8nio/n8n:1.97.1

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=dpg-d1lh1ber433r73dnm8rg-a
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=n8ndb_18up
ENV DB_POSTGRESDB_USER=n8ndb_18up_user
ENV DB_POSTGRESDB_PASSWORD=eg0DovUPcprbJw0cFFFYiKA4egSb5vPC
ENV DB_POSTGRESDB_SCHEMA=public

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=imane
ENV N8N_BASIC_AUTH_PASSWORD=Maroc182000!
ENV GENERIC_TIMEZONE="Europe/Paris"
